#!/usr/bin/env python3
"""
Export one trained model, quantized W8A8 exactly as in eval_quant.py, to:
  OUT/model_weights.h   int8 weights, per-channel weight scales, float biases, activation scales, LayerNorm params
  OUT/inputs.bin        float32 [N][2][22][500]  preprocessed test trials (what the device would receive)
  OUT/labels.bin        int32   [N]
  OUT/ref_logits.bin    float32 [N][4]           PyTorch W8A8 outputs (log-softmax) for bit-level comparison
usage: python src/hw/export_c.py DATA_DIR RUNS_ROOT OUT_DIR KIND SEED SUBJECT [fused]   KIND = loso | calib | calib_ea
'fused' merges the temporal and spatial convolutions into one 22x25 convolution (see quantize.fuse_frontend).
"""
import os
import sys

import numpy as np
import torch

_SRC = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, _SRC)

from alignment.ea_dataset import AlignedMotorImageryDataset  # noqa: E402
from encoder.conformer_braindecode import EEGConformer  # noqa: E402
from hw.quantize import calibrate, quantize  # noqa: E402
from safetensors.torch import load_file  # noqa: E402

DATA, ROOT, OUT = (os.path.abspath(p) for p in sys.argv[1:4])
KIND, SEED, SUBJ = sys.argv[4], int(sys.argv[5]), int(sys.argv[6])
FUSED = len(sys.argv) > 7 and sys.argv[7] == 'fused'
os.makedirs(OUT, exist_ok=True)
os.chdir(os.path.join(os.path.dirname(_SRC), 'scripts'))
FILES = sorted(os.listdir(DATA))[:18]
KW = dict(sample_keys=['inputs', 'attention_mask'], chunk_len=500, num_chunks=2, ovlp=0, root_path=DATA + '/',
          gpt_only=False)
f = SUBJ - 1
if KIND == 'loso':
    align, path = 'none', f'{ROOT}/runs5k/none_s{SEED}-{f}/model_final/model.safetensors'
    train_files, test_files = [x for i, x in enumerate(FILES) if i // 2 != f], FILES[2 * f:2 * f + 2]
else:
    align = 'ea' if KIND == 'calib_ea' else 'none'
    path = f'{ROOT}/calib/{KIND}_s{SEED}_subj{SUBJ}-{f}/model_final/model.safetensors'
    train_files, test_files = [FILES[2 * f + 1]], [FILES[2 * f]]


def tensors(files):
    ds = AlignedMotorImageryDataset(files, align=align, **KW)
    return torch.stack([ds[i]['inputs'] for i in range(len(ds))]), torch.as_tensor(np.asarray(ds.labels)).long()


enc = EEGConformer(n_outputs=4, n_chans=22, n_times=500, ch_pos=None, is_decoding_mode=True)
sd = load_file(path)
enc.load_state_dict({k[len('encoder.'):]: v for k, v in sd.items() if k.startswith('encoder.')})
enc.eval()
q = quantize(enc, 8, 8, fuse=FUSED)
trx, _ = tensors(train_files)
idx = torch.randperm(len(trx), generator=torch.Generator().manual_seed(0))[:256]
calibrate(q, [trx[idx[i:i + 64]] for i in range(0, 256, 64)])
tex, tey = tensors(test_files)
with torch.no_grad():
    ref = torch.cat([q(tex[i:i + 128]) for i in range(0, len(tex), 128)])
print('PyTorch W8A8 accuracy:', float((ref.argmax(1) == tey).float().mean()), 'N =', len(tey))

tex.numpy().astype(np.float32).tofile(f'{OUT}/inputs.bin')
tey.numpy().astype(np.int32).tofile(f'{OUT}/labels.bin')
ref.numpy().astype(np.float32).tofile(f'{OUT}/ref_logits.bin')

lines = ['/* Generated by src/hw/export_c.py: Neuro-GPT encoder-only model, W8A8. Do not edit. */',
         '#ifndef MODEL_WEIGHTS_H', '#define MODEL_WEIGHTS_H', '#include <stdint.h>',
         f'/* model: {os.path.relpath(path, ROOT)} */']
n_int8 = 0


def arr(name, ctype, values, fmt):
    vals = ','.join(fmt(v) for v in values)
    lines.append(f'static const {ctype} {name}[{len(values)}] = {{{vals}}};')


def fl(v):
    return f'{float(v):.9g}f'


def emit_layer(name, ql):
    global n_int8
    w = ql.w_int.reshape(ql.w_int.shape[0], -1).numpy().astype(np.int64).ravel()
    n_int8 += w.size
    arr(f'{name}_w', 'int8_t', w, str)
    arr(f'{name}_ws', 'float', ql.w_scale.numpy(), fl)
    arr(f'{name}_b', 'float', ql.layer.bias.detach().numpy(), fl)
    lines.append(f'#define {name}_as {fl(ql.aq.scale)}')


def emit_ln(name, ln):
    arr(f'{name}_g', 'float', ln.weight.detach().numpy(), fl)
    arr(f'{name}_be', 'float', ln.bias.detach().numpy(), fl)


pe = q.patch_embedding
emit_layer('conv1', pe.shallownet[0])  # fused: [40][22][25]; otherwise [40][25]
if FUSED:
    lines.append('#define FUSED_FRONTEND 1')
else:
    emit_layer('conv2', pe.shallownet[1])
emit_layer('proj', pe.projection[0])
for b, blk in enumerate(q.transformer):
    att, ff = blk[0].fn[1], blk[1].fn[1]
    emit_ln(f'ln1_{b}', blk[0].fn[0])
    emit_layer(f'q_{b}', att.queries)
    emit_layer(f'k_{b}', att.keys)
    emit_layer(f'v_{b}', att.values)
    emit_layer(f'o_{b}', att.projection)
    for nm, aq in (('qa', att.q_aq), ('ka', att.k_aq), ('va', att.v_aq), ('pa', att.p_aq)):
        lines.append(f'#define {nm}_{b}_s {fl(aq.scale)}')
    emit_ln(f'ln2_{b}', blk[1].fn[0])
    emit_layer(f'ff1_{b}', ff[0])
    emit_layer(f'ff2_{b}', ff[3])
emit_layer('fc1', q.fc.fc[0])
emit_layer('fc2', q.fc.fc[3])
emit_layer('fc3', q.final_layer.final_layer[0])
lines += ['#define BLK_TABLE(X) X(0) X(1) X(2) X(3) X(4) X(5)', f'#define N_INT8_WEIGHTS {n_int8}', '#endif']
open(f'{OUT}/model_weights.h', 'w').write('\n'.join(lines) + '\n')
print('int8 weights:', n_int8, '| header:', f'{OUT}/model_weights.h')
